package com.example.Student_Library_Management_System.Services;


import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;

    public String createStudent(Student student){

        //Student from the postman is already the basic attributes set.


        //Card should be autogenerated when createStudent function is called
        Card card=new Card();
        card.setCardStatus(CardStatus.ACTIVATED); //card status is being set
        card.setStudentVariableName(student); //Foreign key attribute


        //let go to the student
        student.setCard(card);

        //If there was a unidirectional mapping : we had to save both of them
        //But we are super advance and are using bidirectional mapping : child will automatically be saved.

        studentRepository.save(student);

        //By cascading effect,child will automatically saved.

        return "Student and Card Added";
    }
}
